annotations:
  artifacthub.io/alternativeName: nexus
  artifacthub.io/changes: |
    - kind: changed
      description: "Updated the Nexus3 OCI image to v3.57.0."
apiVersion: v2
appVersion: 3.57.0
description: Helm chart for Sonatype Nexus 3 OSS.
home: https://www.sonatype.com/nexus-repository-oss
icon: https://help.sonatype.com/docs/files/331022/34537964/3/1564671303641/NexusRepo_Icon.png
keywords:
- artifacts
- dependency
- management
- sonatype
- nexus
- repository
maintainers:
- email: steve.hipwell@gmail.com
  name: stevehipwell
name: nexus3
sources:
- https://github.com/sonatype/docker-nexus3
- https://hub.docker.com/r/sonatype/nexus3
- https://github.com/stevehipwell/helm-charts/
type: application
version: 4.31.0
